# Generated by Django 5.2.5 on 2025-08-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("ordens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservicomodel",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens",
                to="clientes.clientemodel",
            ),
        ),
    ]
